### PR TITLE
Fixed video not playing in center on full screen

### PR DESCRIPTION
**Pull request by prem5102**
Added center widget on top of video player to make video to play on center in full screen mode.

### CODE REVIEW

**Review by Levi-Lesches — APPROVED** [review]
Haven't tested, but I can't see the possible harm in this. Thanks!

**Comment by Levi-Lesches** [comment]
Thanks for your contribution!

**Comment by prem5102** [comment]
And also later make a pull request that makes the Android device to hide the status bar and navigation bar in full screen and lock device orientation in landscape mode while on full screen

**Comment by prem5102** [comment]
Awesome package man, yours are the only package that plays video on full screen without black screen in flutter web.

**Comment by Levi-Lesches** [comment]
> And also later make a pull request that makes the Android device to hide the status bar and navigation bar in full screen and lock device orientation in landscape mode while on full screen

Oh this will be nice, I hate native dev and have little experience with the ins and outs of the platform. 



> Awesome package man, yours are the only package that plays video on full screen without black screen in flutter web.

Thanks! I made this package specifically for Flutter web since I was making a video-hosting site. Also, thanks to your PR I finally bumped the version number to `1.0.0` (just released it)

**Pull request merged**
